Repository webarkit/ARnft, pull requests merged in 2021-11, with the labels that each got.

#237 add targetFrameRate in CameraViewRenderer
  dist/ARnft.js
  dist/src/ARnft.js
  dist/src/ARnft.js.map
  dist/src/NFTWorker.js
  dist/src/NFTWorker.js.map
  dist/src/Worker.js
  dist/src/Worker.js.map
  dist/src/renderers/CameraViewRenderer.js
  dist/src/renderers/CameraViewRenderer.js.map
  dist/src/utils/ARnftUtils.js
  dist/src/utils/ARnftUtils.js.map
  dist/src/utils/html/Container.js
  dist/src/utils/html/Container.js.map
  examples/arNFT_autoupdate_example.html
  examples/config.json
  src/ARnft.ts
  src/NFTWorker.ts
  src/Worker.ts
  src/config/ConfigData.ts
  src/renderers/CameraViewRenderer.ts
  src/utils/ARnftUtils.ts
  src/utils/html/Container.ts
  types/src/ARnft.d.ts
  types/src/NFTWorker.d.ts
  types/src/config/ConfigData.d.ts
  types/src/renderers/CameraViewRenderer.d.ts
  types/src/utils/ARnftUtils.d.ts
  types/src/utils/html/Container.d.ts
Labels: enhancement, code-design

#243 fix issue #242
  dist/ARnft.js
  dist/src/ARnft.js
  dist/src/ARnft.js.map
  dist/src/utils/ARnftUtils.js.map
  dist/src/utils/html/Container.js
  dist/src/utils/html/Container.js.map
  examples/arNFT_autoupdate_example.html
  src/ARnft.ts
  src/utils/ARnftUtils.ts
  src/utils/html/Container.ts
Labels: bug, enhancement

#244 Improves in CameraViewRenderer class and fix for bug #242
  dist/ARnft.js
  dist/package.json
  dist/src/ARnft.js
  dist/src/ARnft.js.map
  dist/src/NFTWorker.js
  dist/src/NFTWorker.js.map
  dist/src/Worker.js
  dist/src/Worker.js.map
  dist/src/renderers/CameraViewRenderer.js
  dist/src/renderers/CameraViewRenderer.js.map
  dist/src/utils/ARnftUtils.js
  dist/src/utils/ARnftUtils.js.map
  dist/src/utils/html/Container.js
  dist/src/utils/html/Container.js.map
  examples/arNFT_autoupdate_example.html
  examples/config.json
  package.json
  src/ARnft.ts
  src/NFTWorker.ts
  src/Worker.ts
  src/config/ConfigData.ts
  src/renderers/CameraViewRenderer.ts
  src/utils/ARnftUtils.ts
  src/utils/html/Container.ts
  types/src/ARnft.d.ts
  types/src/NFTWorker.d.ts
  types/src/config/ConfigData.d.ts
  types/src/renderers/CameraViewRenderer.d.ts
  types/src/utils/ARnftUtils.d.ts
  types/src/utils/html/Container.d.ts
Labels: bug, enhancement, code-design

#245 New initializeRaw function inside ARnft class
  dist/ARnft.js
  dist/src/ARnft.js
  dist/src/ARnft.js.map
  dist/src/NFTWorker.js.map
  dist/src/renderers/CameraViewRenderer.js
  dist/src/renderers/CameraViewRenderer.js.map
  examples/arNFT_initialize_raw_example.html
  examples/js/cameraViewRenderer.js
  src/ARnft.ts
  src/NFTWorker.ts
  src/renderers/CameraViewRenderer.ts
  types/src/ARnft.d.ts
  types/src/renderers/CameraViewRenderer.d.ts
Labels: enhancement, code-design

#247 latest from dev - initializeRaw and new ARnft-threejs 0.4.0 version
  dist/ARnft.js
  dist/package.json
  dist/src/ARnft.js
  dist/src/ARnft.js.map
  dist/src/NFTWorker.js.map
  dist/src/renderers/CameraViewRenderer.js
  dist/src/renderers/CameraViewRenderer.js.map
  examples/Data/models/flamingo/Flamingo.glb
  examples/arNFT_gltf_brave_robot_example.html
  examples/arNFT_gltf_example.html
  examples/arNFT_gltf_flamingo_example.html
  examples/arNFT_initialize_raw_example.html
  examples/js/ARnftThreejs.js
  examples/js/cameraViewRenderer.js
  package.json
  src/ARnft.ts
  src/NFTWorker.ts
  src/renderers/CameraViewRenderer.ts
  types/src/ARnft.d.ts
  types/src/renderers/CameraViewRenderer.d.ts
Labels: enhancement, dependencies, code-design
